version: '3'

services:
  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    image: react-app
    container_name: frontend
    volumes:
      - ./client/:/usr/app
      - /usr/app/node_modules
    ports:
      - "3000:3000"
    depends_on:
      - server
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    image: node-app
    container_name: backend
    env_file: ./server/.env
    volumes:
      - ./server/:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - "5060:5060"